language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - nightly # currently points to 3.6-dev

# command to install dependencies
before_install: sudo apt-get install openmpi-bin libopenmpi-dev

install: pip install -r requirements.txt

# command to run tests
script: py.test
