language: python

python:
    - 2.7
    - 3.5

# command to install dependencies
before_install:
    - sudo apt-get update
    - sudo apt-get install openmpi-bin libopenmpi-dev liblapack-dev glpk-utils libglpk-dev gfortran

install: pip install -r requirements.txt

# command to run tests
script: py.test --doctest-modules --cov-report term-missing --cov=pascal
